channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.0
- pip:
  - mlflow==2.10.0
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==23.2
  - pyyaml==6.0.1
  - scikit-learn==1.5.1
  - scipy==1.14.0
name: mlflow-env
